spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank accounts related Cards Prod APIs "
  contactDetails:
    name: "Willy - Product owner"
    email: "willy@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345